3BIT/ITU/src/smartcity/views/admin.py
"""
File containing functions that renders admin's templates

@author: Ladislav Vašina
@email: xvasin11@stud.fit.vutbr.cz
"""

from flask import Blueprint, request, jsonify, make_response, current_app, render_template
from flask_login import login_required, login_user, logout_user, current_user
from smartcity.views import roles_required
from smartcity.models import User, Role, RolesUsers, ServiceTask, ServiceTaskUsers, Comment, Ticket, TicketStateEnum, db

from .admin_forms import CreateCityManager, EditUser
from .admin_forms import EditUser
admin_bp = Blueprint("admin", __name__)


@admin_bp.route("/admin_dashboard", methods=["GET", "POST"])
@login_required
@roles_required(["admin"])
def admin_dashboard():
    all_users = User.query.all()
    forms_list = []
    for user in all_users:
        edit_form = EditUser(name=user.name, surname=user.surname, email=user.email, role=user.role[0].name)
        forms_list.append(edit_form)
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template("admin/admin_dashboard.html", current_user=current_user, all_users=all_users, form=edit_form,
                           forms_list=forms_list, userProfileForm=edit_form)


@admin_bp.route("/create_city_manager", methods=["GET", "POST"])
@login_required
@roles_required(["admin"])
def create_city_manager():
    create_city_manager_form = CreateCityManager()
    if request.method == "POST":
        if create_city_manager_form.validate():
            response_object = {
                "status": "success", "message": "Form verification successful"
            }
            return jsonify(response_object), 200
        else:
            return jsonify(create_city_manager_form.errors), 400
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template("admin/create_city_manager.html", current_user=current_user, form=create_city_manager_form, userProfileForm=edit_form)

3BIT/ITU/src/smartcity/views/auth.py
"""
File containing functions that renders login and signup templates

@author: Dominik Vágner
@email: xvagne10@stud.fit.vutbr.cz
"""

from flask import Blueprint, render_template, request, jsonify, make_response, flash
from flask_login import current_user

from smartcity.views.auth_forms import LoginForm, SignupForm

auth_bp = Blueprint("auth", __name__)


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    login_form = LoginForm()
    if request.method == "POST":
        if login_form.validate():
            response_object = {
                "status": "success", "message": "Form verification successful"
            }
            return jsonify(response_object), 200
        else:
            return jsonify(login_form.errors), 400
    return render_template("public/login.html", form=login_form)


@auth_bp.route("/signup", methods=["GET", "POST"])
def signup():
    signup_form = SignupForm()
    if request.method == "POST":
        if signup_form.validate():
            response_object = {
                "status": "success", "message": "Form verification successful"
            }
            return jsonify(response_object), 200
        else:
            return jsonify(signup_form.errors), 400
    return render_template("public/signup.html", form=signup_form)

3BIT/ITU/src/smartcity/views/home.py
"""
File contains function that renders main page template

@author: Dominik Vágner
@email: xvagne10@stud.fit.vutbr.cz
"""

from flask import Blueprint, render_template
from flask_login import current_user, login_required
from smartcity.views import roles_required
from smartcity.models import Role, User

from .admin_forms import EditUser

home_bp = Blueprint("home", __name__)


@home_bp.route("/", methods=["GET", "POST"])
def index():
    roles = Role.query.all()
    if current_user.is_anonymous:
        users = None
    else:
        users = User.query.filter_by(email=current_user.email).first()
    if current_user.is_authenticated:
        edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
        return render_template("public/index.html", roles=roles, users=users, current_user=current_user, userProfileForm=edit_form)
    else:
        return render_template("public/index.html", roles=roles, users=users, current_user=current_user)

3BIT/ITU/src/smartcity/views/manager.py
"""
File containing functions that renders manager's templates

@author: Ladislav Vašina
@email: xvasin11@stud.fit.vutbr.cz

@author: Dominik Vágner
@email: xvagne10@stud.fit.vutbr.cz
"""

from flask import Blueprint, request, jsonify, make_response, current_app, render_template
from flask_login import login_required, login_user, logout_user, current_user
from smartcity.views import roles_required
from smartcity.models import User, Role, RolesUsers, ServiceTask, ServiceTaskUsers, Comment, Ticket, TicketStateEnum, db

from smartcity.views.manager_forms import CreateTechnician, CreateServiceTask, CreateNotice
from .admin_forms import EditUser
manager_bp = Blueprint("manager", __name__)


@manager_bp.route("/manager_dashboard", methods=["GET", "POST"])
@login_required
@roles_required(["manager"])
def manager_dashboard():
    tickets = Ticket.query.all()
    all_users = User.query.all()
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template("manager/manager_dashboard.html", current_user=current_user, tickets=tickets,
                           all_users=all_users, userProfileForm=edit_form)


@manager_bp.route("/create_technician", methods=["GET", "POST"])
@login_required
@roles_required(["manager"])
def create_technician():
    create_technician_form = CreateTechnician()
    if request.method == "POST":
        if create_technician_form.validate():
            response_object = {
                "status": "success", "message": "Form verification successful"
            }
            return jsonify(response_object), 200
        else:
            return jsonify(create_technician_form.errors), 400
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template("manager/create_technician.html", current_user=current_user, form=create_technician_form, userProfileForm=edit_form)


@manager_bp.route("/create_service_task", methods=["GET", "POST"])
@login_required
@roles_required(["manager"])
def create_service_task():
    tickets = Ticket.query.all()
    service_technicians = User.query.join(RolesUsers).filter(RolesUsers.role_id == 2).all()
    create_service_task_form = CreateServiceTask(service_technicians)
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template("manager/create_service_task.html", current_user=current_user, form=create_service_task_form,
                           service_technicians=service_technicians, tickets=tickets, userProfileForm=edit_form)


@manager_bp.route("/manager_ticket_view", methods=["GET", "POST"])
@login_required
@roles_required(["manager"])
def manager_ticket_view():
    if request.method == "GET":
        ticket_comments = Comment.query.filter_by(ticket_id=request.args.get("ticketId")).all()
        tickets_tasks = ServiceTask.query.filter_by(parent_ticket=request.args.get("ticketId")).all()
        try:
            selected_ticket_id = int(request.args.get("ticketId"))
        except Exception as e:
            return render_template("204.html")
    tickets = Ticket.query.all()
    all_users = User.query.all()
    service_technicians = User.query.join(RolesUsers).filter(RolesUsers.role_id == 2).all()
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template("manager/manager_ticket_view.html", current_user=current_user,
                           service_technicians=service_technicians, tickets=tickets,
                           selected_ticket_id=selected_ticket_id, all_users=all_users, ticket_comments=ticket_comments,
                           tickets_tasks=tickets_tasks, userProfileForm=edit_form)


@manager_bp.route("/manager_message_board", methods=["GET", "POST"])
@login_required
@roles_required(["manager"])
def manager_message_board():
    create_notice_form = CreateNotice()
    if request.method == "POST":
        if create_notice_form.validate():
            response_object = {
                "status": "success", "message": "Form verification successful"
            }
            return jsonify(response_object), 200
        else:
            return jsonify(create_notice_form.errors), 400
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template(
        "manager/manager_message_board.html",
        current_user=current_user,
        userProfileForm=edit_form,
        create_form=create_notice_form
    )

3BIT/ITU/src/smartcity/templates/204.html
<!--
File containing 204 page

@author: Ladislav Vašina
@email: xvasin11@stud.fit.vutbr.cz
-->

{% extends "layout.html" %}

{% block title %} No content {% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <div>
            <h1><a href="https://http.cat/204" style="text-decoration: none;color:black;">204</a></h1>
            <p>No content here. </p>
            <a href="javascript:history.back()">GO BACK</a>
        </div>
    </div>
</div>
{% endblock %}

3BIT/ITU/src/smartcity/templates/401.html
<!--
File containing 401 page

@author: Dominik Vágner
@email: xvagne10@stud.fit.vutbr.cz
-->

{% extends "layout.html" %}

{% block title %} Unauthorized {% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <div>
            <h1>401</h1>
            <p>You aren't authorized to see this page. Please <a href="{{ url_for("auth.login") }}">log in</a> first.</p>
        </div>
    </div>
</div>
{% endblock %}

3BIT/ITU/src/smartcity/templates/footer.html
<!--
File containing website footer

@author: Dominik Vágner
@email: xvagne10@stud.fit.vutbr.cz
-->

<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                <i class="las la-city" style="font-size: 22px"></i>
            </a>
            <span class="mb-3 mb-md-0 text-muted">&copy; 2022 Smartcity</span>
        </div>
    </footer>
</div>

3BIT/ITU/src/smartcity/templates/header.html
<!--
File containing page header

@author: Dominik Vágner
@email: xvagne10@stud.fit.vutbr.cz

@author: Ladislav Vašina
@email: xvasin11@stud.fit.vutbr.cz
-->

{% from "macros/fields.html" import render_text_field, render_boolean_field, render_alert, render_specific_id_text_field %}

<div class="container">
    <header class="py-3 border-bottom sticky-top mb-4">
        <nav id="navbar-main" class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <a href="{{ url_for("home.index") }}" class="navbar-brand text-dark text-decoration-none mr-5">
                    <i class="las la-city" style="font-size: 32px"></i><b style="font-size: 26px; margin-left: 10px">Smartcity</b>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler01"
                        aria-controls="navbarToggler01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarToggler01">
                    <ul class="navbar-nav me-auto mb-2 justify-content-center mb-md-0">
                        {% if not current_user.is_authenticated %}
                            <li class="nav-item"><a href="#scrollspyHeading1" class="nav-link px-2 link-dark">Home</a></li>
                            <li class="nav-item"><a href="#scrollspyHeading2" class="nav-link px-2 link-dark">FAQ</a></li>
                            <li class="nav-item"><a href="#scrollspyHeading3" class="nav-link px-2 link-dark">Contact</a></li>
                        {% endif %}
                        {% if current_user.is_authenticated %}
                            {% if current_user.role[0].name == 'manager' %}
                                <li class="nav-item"><a href="{{ url_for("manager.manager_dashboard") }}"
                                                        class="nav-link px-2 link-dark">Dashboard</a></li>
                                <li class="nav-item"><a href="{{ url_for("manager.manager_message_board") }}"
                                                        class="nav-link px-2 link-dark">Message Board</a></li>
                                <li class="nav-item"><a href="{{ url_for("manager.create_technician") }}"
                                                        class="nav-link px-2 link-dark">Create technician</a></li>
                                <li class="nav-item"><a href="{{ url_for("manager.create_service_task") }}"
                                                        class="nav-link px-2 link-dark">Create service task</a></li>
                            {% endif %}
                        {% endif %}
                        {% if current_user.is_authenticated %}
                            {% if current_user.role[0].name == 'admin' %}
                                <li class="nav-item"><a href="{{ url_for("admin.admin_dashboard") }}"
                                                        class="nav-link px-2 link-dark">Dashboard</a></li>
                                <li class="nav-item"><a href="{{ url_for("admin.create_city_manager") }}"
                                                        class="nav-link px-2 link-dark">Create city manager</a></li>
                            {% endif %}
                        {% endif %}
                        {% if current_user.is_authenticated %}
                            {% if current_user.role[0].name == 'resident' %}
                                <li class="nav-item"><a href="{{ url_for("resident.map_of_tickets") }}"
                                                        class="nav-link px-2 link-dark">Map of tickets</a></li>
                                <li class="nav-item"><a href="{{ url_for("resident.my_tickets") }}"
                                                        class="nav-link px-2 link-dark">My tickets</a></li>
                                <li class="nav-item"><a href="{{ url_for("resident.new_ticket") }}"
                                                        class="nav-link px-2 link-dark">New ticket</a></li>
                                <li class="nav-item"><a href="{{ url_for("resident.resident_message_board") }}"
                                                        class="nav-link px-2 link-dark">Message Board</a></li>
                            {% endif %}
                        {% endif %}
                        {% if current_user.is_authenticated %}
                            {% if current_user.role[0].name == 'technician' %}
                                <li class="nav-item"><a href="{{ url_for("technician.assigned_tasks") }}"
                                                        class="nav-link px-2 link-dark">Assigned tasks</a></li>
                            {% endif %}
                        {% endif %}
                    </ul>

                    <div class="text-left align-items-center">
                        <div class="nav-item mt-2">
                            {% if current_user.is_anonymous %}
                                <a href="{{ url_for("auth.login") }}"><button type="button" class="btn btn-outline-light me-2" style="border-color: #96031A; color: #96031A">Login</button></a>
                                <a href="{{ url_for("auth.signup") }}"><button type="button" class="btn btn-primary" style="background-color: #96031A; border-color: #96031A;">Sign-Up</button></a>
                            {% else %}
                                <div class="nav-item dropdown">
                                    <a class="caret dropdown-toggle d-block link-dark text-decoration-none" style="outline: 0;" data-bs-toggle="dropdown" aria-expanded="false" id="usernameInHeader">
                                        <i class="las la-user" style="font-size: 24px"></i>{{ current_user.fullname }}
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" data-bs-toggle="modal"
                                               data-bs-target="#userProfileModal">Profile</a></li>
                                        <li><a class="dropdown-item" data-bs-toggle="modal"
                                               data-bs-target="#logoutModal">Logout</a></li>
                                    </ul>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
</div>

{% if current_user.is_authenticated %}
<!-- START User profile modal -->
<div class="modal fade" id="userProfileModal" tabindex="-1"
     aria-hidden="true"
     style="z-index: 999999999;">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">User profile</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body py-0">
                <form id="editUserForm{{ current_user.id }}" class="mb-3 mt-md-4" method="POST">
                    {# CSRF Token #}
                    {{ userProfileForm.csrf_token() }}
                    <div id="csrf_token_error" class="text-danger"></div>
                    {# userProfileForm fields #}
                    <div class="mb-3 row">
                        <div class="col">
                            {{ render_specific_id_text_field(userProfileForm.name, "name" ~ current_user.id, current_user.id, userProfileForm.name.object_data ) }}
                        </div>
                        <div class="col">
                            {{ render_specific_id_text_field(userProfileForm.surname, "surname" ~ current_user.id, current_user.id, userProfileForm.surname.object_data ) }}
                        </div>
                    </div>
                    <div class="mb-3">
                        {{ render_specific_id_text_field(userProfileForm.email, "email" ~ current_user.id, current_user.id, userProfileForm.email.object_data ) }}
                    </div>
                    <div class="mb-3">
                        {{ render_specific_id_text_field(userProfileForm.password, "password" ~ current_user.id, current_user.id ) }}
                    </div>
                    <div class="form-check">
                        <input class="form-check-input checkBox{{ current_user.id }}" type="checkbox"
                               value="" id="showPassCheckBox"
                               onclick="showPassword('{{ current_user.id }}')">
                        <label class="form-check-label" for="showPassCheckBox">
                            Show password
                        </label>
                    </div>
                    <div class="d-grid mt-5">
                        <button class="btn btn-outline-dark updateUserInfoBtn" type="submit" id="updateUserBtn">
                            Update your information
                        </button>
                    </div>
                </form>
                <div id="user-edit-alerts" class="mt-3"></div>
                <div id="user-edit-success-message" style="display: none;"></div>
            </div>
        </div>
    </div>
</div>
<!-- END User profile modal -->
{% endif %}

{% block js %}
    <script>
        function showPassword(id) {
            let x = document.getElementById("password" + id);
            if (x.type === "password") {
                x.type = "text";
            } else {
                x.type = "password";
            }
        }
        let y = document.getElementById("email" + {{ current_user.id }});
        y.disabled = true;

        const user_edit_form = document.getElementById("editUserForm" + {{ current_user.id }});
        const user_edit_successMessage = document.getElementById("user-edit-success-message");
        const user_edit_alerts = document.getElementById("user-edit-alerts");
        const user_edit_fields = {
            csrf_token: {
                input: document.getElementById('csrf_token'),
                error: document.getElementById('csrf_token-error')
            },
            user_id: {{ current_user.id }},
            name: {
                input: document.getElementById('name' + {{ current_user.id }}),
                error: document.getElementById('name-error-' + {{ current_user.id }})
            },
            surname: {
                input: document.getElementById('surname' + {{ current_user.id }}),
                error: document.getElementById('surname-error-' + {{ current_user.id }})
            },
            email: {
                input: document.getElementById('email' + {{ current_user.id }}),
                error: document.getElementById('email-error-' + {{ current_user.id }})
            },
            password: {
                input: document.getElementById('password' + {{ current_user.id }}),
                error: document.getElementById('password-error-' + {{ current_user.id }})
            },
            confirm: {
                input: document.getElementById('confirm' + {{ current_user.id }}),
                error: document.getElementById('confirm-error-' + {{ current_user.id }})
            }
        }
        // React to form submission
        user_edit_form.addEventListener("submit", async (e) => {
                e.preventDefault();
                $('#userProfileModal').modal('toggle');
                // Make JSON out of the form input value
                let data = JSON.stringify({
                    csrf_token: user_edit_fields.csrf_token.input.value,
                    user_id: user_edit_fields.user_id,
                    name: user_edit_fields.name.input.value,
                    surname: user_edit_fields.surname.input.value,
                    email: user_edit_fields.email.input.value,
                    password: user_edit_fields.password.input.value,
                });

                const response = await fetch("#", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: data,
                });

                if (response.ok) {
                    const api_response = await fetch("{{ url_for("api.auth_api.edit_user") }}", {
                        method: "POST",
                        headers: {
                            "Content-Type": "application/json"
                        },
                        body: data,
                    });
                        let usernameTextToEdit = document.getElementById("usernameInHeader")
                        console.log('<i class="las la-user" style="font-size: 24px"></i>' + user_edit_fields.name.input.value + ' ' + user_edit_fields.surname.input.value);
                        usernameTextToEdit.innerHTML = '<i class="las la-user" style="font-size: 24px"></i>' + user_edit_fields.name.input.value + ' ' + user_edit_fields.surname.input.value;
                    if (api_response.ok) {

                    } else {
                        const message = await api_response.json();
                        user_edit_alerts.innerHTML = bootstrap_alert_macro(message["message"], "danger")
                    }
                }
            }
        )
        ;
    </script>
{% endblock %}

3BIT/ITU/src/smartcity/templates/layout.html
<!--
File containing website layout

@author: Dominik Vágner
@email: xvagne10@stud.fit.vutbr.cz
-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head %}
    <title>{% block title %}Smartcity{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>
    <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/3253/3253488.png">
    <link rel="stylesheet" href="../static/css/main.css">
    {% block css %}
    {% endblock %}

    {% endblock %}
</head>
<body>
    {% block body %}
        {% include "header.html" %}

        {% block menu %}
        {% endblock %}

        <div id="content">
            {% block content %}
            {% endblock %}
        </div>

        <div>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == 'message' %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {{ message }}
                        </div>
                    {% else %}
                        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}
        </div>

        {% include "footer.html" %}
    <!-- Body end block -->
    {% endblock %}
    {% block scripts %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
        <script type="text/javascript" src="https://api.mapy.cz/loader.js"></script>
        <script type="text/javascript">Loader.load();</script>
        <script src="../static/js/main.js"></script>
    {% endblock %}
    {% block js %}
    {% endblock %}
</body>

<!-- Modals -->
<!-- Logout Modal -->
<div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel" aria-hidden="true" style="z-index: 999999999;">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header" style="border-bottom: none; padding-bottom: 0px">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Are you sure you want to log out?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body py-0">
                <hr>
            </div>
            <div class="modal-footer" style="border-top: none; padding-top: 0px;">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="logout_submit" type="button" class="btn btn-primary" style="background-color: #96031A; border-color: #96031A;">Log out</button>
            </div>
        </div>
    </div>
</div>

{% block modals %}
{% endblock %}

</html>