3BIT/ITU/src/smartcity/views/resident.py
"""
File containing functions that renders resident's views

@author: David Novák
@email: xnovak2r@stud.fit.vutbr.cz
"""

from flask import Blueprint, request, jsonify, make_response, current_app, render_template
from flask_login import login_required, login_user, logout_user, current_user
from sqlalchemy import desc

from smartcity.models import User, Role, RolesUsers, ServiceTask, ServiceTaskUsers, Comment, Ticket, TicketStateEnum, db
from smartcity.views import roles_required
from smartcity.views.resident_forms import *
from .admin_forms import EditUser

resident_bp = Blueprint("resident", __name__)


@resident_bp.route("/new_ticket", methods=["GET", "POST"])
@login_required
@roles_required(["resident"])
def new_ticket():
    create_new_ticket_form = NewTicket()
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template("resident/new_ticket.html", current_user=current_user, form=create_new_ticket_form,
                           userProfileForm=edit_form)


@resident_bp.route("/my_tickets", methods=["GET", "POST"])
@login_required
@roles_required(["resident"])
def my_tickets():
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    tickets = Ticket.query.filter(Ticket.reporter_id == current_user.id).order_by(desc(Ticket.id)).all()
    return render_template("resident/my_tickets.html", current_user=current_user, tickets=tickets,
                           userProfileForm=edit_form)


@resident_bp.route("/map_of_tickets", methods=["GET", "POST"])
@login_required
@roles_required(["resident"])
def map_of_tickets():
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template("resident/map_of_tickets.html", current_user=current_user, userProfileForm=edit_form)


@resident_bp.route("/ticket_view", methods=["GET", "POST"])
@login_required
@roles_required(["resident"])
def ticket_view():
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    ticket = Ticket.query.filter(Ticket.id == int(request.args.get("ticketID"))).all()
    ticket_comments = Comment.query.join(Ticket).filter(Ticket.id == int(request.args.get("ticketID"))).all()
    all_users = User.query.all()
    return render_template("resident/ticket_view.html", current_user=current_user, ticket=ticket,
                           ticket_comments=ticket_comments, userProfileForm=edit_form, all_users=all_users)


@resident_bp.route("/resident_message_board", methods=["GET", "POST"])
@login_required
@roles_required(["resident"])
def resident_message_board():
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template("resident/resident_message_board.html", current_user=current_user, userProfileForm=edit_form)

3BIT/ITU/src/smartcity/views/resident_forms.py
"""
File containing forms for resident's views

@author: David Novák
@email: xnovak2r@stud.fit.vutbr.cz
"""

from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, IntegerField, FileField
from wtforms.validators import DataRequired, Length, InputRequired


class NewTicket(FlaskForm):
    name = StringField("Name", [DataRequired()])
    description = TextAreaField("Description",
                                validators=[InputRequired(message="Please, tell us more about the problem"),
                                            Length(max=2048, message="Description is too long"),
                                            Length(min=20, message="Description is too short")])
    image = StringField("Image", [])
    reporter_id = IntegerField("Reporter_id", [DataRequired()])

3BIT/ITU/src/smartcity/templates/resident/map_of_tickets.html
<!--
Map of tickets

@author: Dominik Vágner
@email: xvagne10@stud.fit.vutbr.cz
-->

{% extends "layout.html" %}
{% from "macros/fields.html" import render_text_field, render_boolean_field, render_alert %}

{% block title %} Map of tickets {% endblock %}

{% block content %}
    <div class="vh-75 d-flex justify-content-center align-items-center">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="mb-4 col-10">
                    <label for="filterStates"><h4>State of tickets you want to be shown</h4></label>
                    <select class="form-select mt-2" aria-label="State-filter" id="filterStates">
                        <option value="All states" selected>All states</option>
                        <option value="New">New</option>
                        <option value="Planned">Planned</option>
                        <option value="WorkInProgress">Work in progress</option>
                        <option value="Done">Done</option>
                    </select>
                </div>
                <div class="mb-3 col-10 ">
                    <div class="card min-vh-100">
                        <div class="card-body" id="map-of-tickets"></div>
                    </div>
                </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function () {
            $('#filterStates').change(function () {
                if ($('#filterStates').val() == 'All states') {
                    $('.marker-new').show();
                    $('.marker-wip').show();
                    $('.marker-planned').show();
                    $('.marker-done').show();
                } else if ($('#filterStates').val() == 'New') {
                    $('.marker-new').show();
                    $('.marker-wip').hide();
                    $('.marker-planned').hide();
                    $('.marker-done').hide();
                } else if ($('#filterStates').val() == 'Planned') {
                    $('.marker-new').hide();
                    $('.marker-wip').hide();
                    $('.marker-planned').show();
                    $('.marker-done').hide();
                } else if ($('#filterStates').val() == 'WorkInProgress') {
                    $('.marker-new').hide();
                    $('.marker-wip').show();
                    $('.marker-planned').hide();
                    $('.marker-done').hide();
                } else if ($('#filterStates').val() == 'Done') {
                    $('.marker-new').hide();
                    $('.marker-wip').hide();
                    $('.marker-planned').hide();
                    $('.marker-done').show();
                }
            });
        });
    </script>
{% endblock %}

3BIT/ITU/src/smartcity/templates/resident/my_tickets.html
<!--
File containing user's tickets

@author: David Novák
@email: xnovak2r@stud.fit.vutbr.cz
-->

{% extends "layout.html" %}
{% from "macros/fields.html" import render_text_field, render_boolean_field, render_alert %}

{% block title %} My tickets {% endblock %}

{% block content %}
    {% if not tickets %}
        <div class="container">
        <div class="row">
            <div class="d-flex justify-content-center align-items-center mt-3 mb-4">
                <b>YOU HAVE NOT CREATED ANY TICKETS</b>
            </div>
        </div>
        <div class="row">
            <div class="d-flex justify-content-center align-items-center mt-3 mb-5">
                <a class="btn btn-outline-dark col-6" href="{{url_for("resident.new_ticket") }}">CREATE TICKET</a>
            </div>
        </div>
        </div>
    {% else %}
    {% for ticket in tickets %}
        <div class="d-flex justify-content-center align-items-center mt-4">
            <div class="card col-10 {{ ticket.state.value }}" style="max-width: 1000px;">
                <div class="row g-0">
                    <div class="col-md-4 d-flex justify-content-center align-items-center">
                        <img
                                {% if ticket.image_path != None %}
                                    src="{{ ticket.image_path }}"
                                {% else %}
                                    src="/static/images/No_image_available.svg.png"
                                {% endif %}
                                    class="img-fluid rounded-start"
                                    alt="{{ ticket.image_path }}"
                                    style="height: 200px; object-fit: fill;"
                        >
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">
                                    <h5 class="card-title"><b>{{ ticket.name }}</b></h5>
                                    <p class="card-text">{{ ticket.description[:120] }}</p>
                                </div>
                                <div class="col-md-4">
                                    <button class="state btn p-2 mt-1 mb-3" type="button"
                                            style="float:right; pointer-events: none;">{{ ticket.state.value }}</button>
                                    <p class="card-text" style="float:right;">{{ ticket.created_at }}</p>
                                    <a class="btn p-2 mt-1 btn-secondary" type="button"
                                       style="float:right; width: 146px;" data-bs-target="#ticket{{ ticket.id }}"
                                       href="{{ url_for("resident.ticket_view") }}?ticketID={{ ticket.id }}">
                                        <b>Details</b>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}

{% block js %}
    <script>
        let statesList = document.getElementsByClassName("state");

        for (let i = 0; i < statesList.length; i++) {
            statesList[i].style.fontWeight = "bold";
            if (statesList[i].innerHTML === "New") {
                statesList[i].style.color = "white";
                statesList[i].style.width = "146px";
                statesList[i].classList.add("btn-danger");
            } else if (statesList[i].innerHTML === "Planned") {
                statesList[i].style.color = "black";
                statesList[i].style.width = "146px";
                statesList[i].classList.add("btn-info");
            } else if (statesList[i].innerHTML === "Work In Progress") {
                statesList[i].style.color = "black";
                statesList[i].classList.add("btn-warning");
            } else if (statesList[i].innerHTML === "Done") {
                statesList[i].style.color = "white";
                statesList[i].style.width = "146px";
                statesList[i].classList.add("btn-success");
            }
        }
    </script>
{% endblock %}

3BIT/ITU/src/smartcity/templates/resident/new_ticket.html
<!--
File containing new tickets

@author: David Novák
@email: xnovak2r@stud.fit.vutbr.cz
-->

{% extends "layout.html" %}
{% from "macros/fields.html" import render_text_field, render_boolean_field, render_alert %}

{% block title %} New ticket {% endblock %}

{% block content %}
    <div class="vh-75 d-flex justify-content-center align-items-center">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-12 col-md-10 col-lg-8">
                    <div class="card bg-white shadow-lg" style="border-radius: 0">
                        <div class="card-body p-5">
                            <form id="form" class="mb-3 mt-md-4" method="POST" enctype="multipart/form-data" novalidate>
                                <i class="las la-city" style="font-size: 36px"></i><b
                                    style="font-size: 32px; margin-left: 10px">SMARTCITY</b>
                                <p class="mt-3 mb-4 mt-1">Create new ticket!</p>
                                {# CSRF Token #}
                                {{ form.csrf_token() }}
                                <div id="csrf_token_error" class="text-danger"></div>
                                {# Form fields #}
                                <input hidden type="number" value="{{ current_user.id }}" id="reporter_id">
                                <div class="mb-3">
                                    <label class="form-label" for="name">Type</label>
                                    <select class="form-select" id="name">
                                        <option value="Traffic Signs">Traffic Signs</option>
                                        <option value="Lighting">Lighting</option>
                                        <option value="Wreck">Wreck</option>
                                        <option value="Greenery">Greenery</option>
                                        <option value="Dump/Garbage">Dump/Garbage</option>
                                        <option value="Bench/Railing/Fence">Bench/Railing/Fence</option>
                                        <option value="Public Transport">Public Transport</option>
                                        <option value="Road">Road</option>
                                        <option value="Sidewalk">Sidewalk</option>
                                        <option value="Other">Other</option>
                                    </select>
                                </div>
                                <div class="mb-3">
                                    {{ render_text_field(form.description) }}
                                </div>
                                <div class="mb-3">
                                    <label for="upload_image" class="form-label">Image</label> <br>
                                    <input type="file" class="form-control form-control-sm" id="upload_image"
                                           accept="image/*"/>
                                </div>

                                <input hidden id="latitude" type="number" name="latitude" value="-1000">
                                <input hidden id="longitude" type="number" name="longitude" value="-1000">
                                <div class="mb-3 mt-4">
                                    <label class="form-label">Location</label> <br>
                                    <a id="map-my-location" class="btn btn-dark w-100 mb-2">Report defect on my
                                        location</a>
                                    <div class="card">
                                        <div class="card-header" id="new-ticket-location">
                                            Please move the marker to the correct location.
                                        </div>
                                        <div class="card-body p-0">
                                            <div class="w-100" style="height: 380px" id="new-ticket-map"></div>
                                        </div>
                                    </div>
                                </div>

                                <div class="d-grid mt-5">
                                    <button class="btn btn-outline-dark" type="submit">Create new ticket</button>
                                </div>
                            </form>
                            <div id="alerts" class="mt-3"></div>
                            <div id="success-message"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script>
        const form = document.getElementById("form")
        const successMessage = document.getElementById("success-message");
        const alerts = document.getElementById("alerts");
        let img = "";
        document.querySelector('#upload_image').addEventListener('change', function () {
            const reader = new FileReader();
            reader.readAsDataURL(this.files[0]);
            reader.addEventListener("load", () => {
                img = reader.result;
            })
        })
        const fields = {
            csrf_token: {
                input: document.getElementById('csrf_token'),
                error: document.getElementById('csrf_token-error')
            },
            reporter_id: {
                input: document.getElementById('reporter_id'),
                error: document.getElementById('reporter_id-error')
            },
            name: {
                input: document.getElementById('name'),
                error: document.getElementById('name-error')
            },
            description: {
                input: document.getElementById('description'),
                error: document.getElementById('description-error')
            },
        }
        const hidden_fields = {
            latitude: {
                input: document.getElementById('latitude'),
            },
            longitude: {
                input: document.getElementById('longitude'),
            },
        }
        // React to form submission
        form.addEventListener("submit", async (e) => {
            e.preventDefault();
            // Make JSON out of the form input value
            let data = JSON.stringify({
                csrf_token: fields.csrf_token.input.value,
                reporter_id: fields.reporter_id.input.value,
                name: fields.name.input.value,
                description: fields.description.input.value,
                latitude: hidden_fields.latitude.input.value,
                longitude: hidden_fields.longitude.input.value,
                image: img,
            });
            const response = await fetch("{{ url_for("resident.new_ticket") }}", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: data,
            });
            for (let key in fields) {
                if (fields[key].input.classList.contains("is-invalid")) {
                    fields[key].input.classList.remove("is-invalid");
                    fields[key].error.innerText = "";
                }
            }
            if (response.ok) {
                const api_response = await fetch("{{ url_for("api.auth_api.create_new_ticket") }}", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: data,
                });

                if (api_response.ok) {
                    window.location.assign("{{ url_for("resident.my_tickets") }}")
                } else {
                    const message = await api_response.json();
                    alerts.innerHTML = bootstrap_alert_macro(message["message"], "danger")
                }
            } else {
                const errors = await response.json();
                Object.keys(errors).forEach((key) => {
                    fields[key].input.classList.add("is-invalid");
                    fields[key].error.innerText = errors[key][0];
                });
            }
        });
    </script>
{% endblock %}

3BIT/ITU/src/smartcity/templates/resident/resident_message_board.html
<!--
File containing resident's view of the message board.

@author: Dominik Vágner
@email: xvagne10@stud.fit.vutbr.cz
-->

{% extends "layout.html" %}
{% from "macros/fields.html" import render_text_field, render_boolean_field, render_alert %}

{% block title %} Message Board {% endblock %}

{% block content %}
    <div class="container">
        <div class="col-12 mb-4" style="max-height: 1000px;">
            <div class="card mb-4" style="height: 60%">
                <div class="card-body pt-0 px-0 h-50">
                    <div class="card-header">
                        <div class="d-flex mt-2 align-items-center">
                            <h3 class="me-auto mb-0">Notice Board</h3>
                        </div>
                        <hr class="w-100 mb-1">
                        <div class="d-inline-flex flex-row align-items-center flex-wrap">
                            <label for="filter_states" class="mt-2">Type of Notice</label>
                            <select class="mx-3 mt-2 form-select" style="width: max-content" aria-label="state-filter" id="filter_states">
                                <option value="All Types" selected>All Types</option>
                                <option value="Announcement">Announcement</option>
                                <option value="Extraordinarity">Extraordinarity</option>
                                <option value="Maintenance">Maintenance</option>
                                <option value="Closure">Closure</option>
                            </select>
                            <label for="date_from" class="mt-2">Date Range</label>
                            <input type="text" class="ms-3 mt-2 form-control" id="daterange" style="width: 225px">
                        </div>
                    </div>
                    <div class="card-body overflow-auto" style="height:90%" id="notices"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
    <script>
        // Render the notices
        const notices = document.getElementById("notices");
        async function renderNotices() {
            notices.innerHTML = "";
            const data = JSON.stringify({
                type: document.getElementById("filter_states").value,
                daterange: document.getElementById("daterange").value,
            });
            const response = await fetch("{{ url_for("api.auth_api.query_notices") }}", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: data,
            });
            const response_message = await response.json();
            const notices_data = eval(response_message);
            if (notices_data.length === 0) {
                notices.innerHTML = "<div class='text-center pt-4'>No notices found.</div>";
                console.log("No notices found.");
            } else {
                eval(notices_data).forEach((notice) => {
                    notices.innerHTML += notice_card_macro(notice);
                });
            }
        }

        // Load the notices on page load
        window.onload = async (e) => {
            await renderNotices();
        }

        // React to the type of notice filter
        document.getElementById("filter_states").addEventListener("change" , async (e) => {
            await renderNotices();
        });

        // React to date range picker apply for filtering the notices
        document.getElementById("daterange").addEventListener("apply.", async (e) => {
            await renderNotices();
        });
        $('#daterange').on('apply.daterangepicker', async function(ev, picker) {
            await renderNotices();
        });
    </script>
{% endblock %}