3BIT/ITU/src/smartcity/views/manager.py
"""
File containing functions that renders manager's templates

@author: Ladislav Vašina
@email: xvasin11@stud.fit.vutbr.cz

@author: Dominik Vágner
@email: xvagne10@stud.fit.vutbr.cz
"""

from flask import Blueprint, request, jsonify, make_response, current_app, render_template
from flask_login import login_required, login_user, logout_user, current_user
from smartcity.views import roles_required
from smartcity.models import User, Role, RolesUsers, ServiceTask, ServiceTaskUsers, Comment, Ticket, TicketStateEnum, db

from smartcity.views.manager_forms import CreateTechnician, CreateServiceTask, CreateNotice
from .admin_forms import EditUser
manager_bp = Blueprint("manager", __name__)


@manager_bp.route("/manager_dashboard", methods=["GET", "POST"])
@login_required
@roles_required(["manager"])
def manager_dashboard():
    tickets = Ticket.query.all()
    all_users = User.query.all()
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template("manager/manager_dashboard.html", current_user=current_user, tickets=tickets,
                           all_users=all_users, userProfileForm=edit_form)


@manager_bp.route("/create_technician", methods=["GET", "POST"])
@login_required
@roles_required(["manager"])
def create_technician():
    create_technician_form = CreateTechnician()
    if request.method == "POST":
        if create_technician_form.validate():
            response_object = {
                "status": "success", "message": "Form verification successful"
            }
            return jsonify(response_object), 200
        else:
            return jsonify(create_technician_form.errors), 400
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template("manager/create_technician.html", current_user=current_user, form=create_technician_form, userProfileForm=edit_form)


@manager_bp.route("/create_service_task", methods=["GET", "POST"])
@login_required
@roles_required(["manager"])
def create_service_task():
    tickets = Ticket.query.all()
    service_technicians = User.query.join(RolesUsers).filter(RolesUsers.role_id == 2).all()
    create_service_task_form = CreateServiceTask(service_technicians)
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template("manager/create_service_task.html", current_user=current_user, form=create_service_task_form,
                           service_technicians=service_technicians, tickets=tickets, userProfileForm=edit_form)


@manager_bp.route("/manager_ticket_view", methods=["GET", "POST"])
@login_required
@roles_required(["manager"])
def manager_ticket_view():
    if request.method == "GET":
        ticket_comments = Comment.query.filter_by(ticket_id=request.args.get("ticketId")).all()
        tickets_tasks = ServiceTask.query.filter_by(parent_ticket=request.args.get("ticketId")).all()
        try:
            selected_ticket_id = int(request.args.get("ticketId"))
        except Exception as e:
            return render_template("204.html")
    tickets = Ticket.query.all()
    all_users = User.query.all()
    service_technicians = User.query.join(RolesUsers).filter(RolesUsers.role_id == 2).all()
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template("manager/manager_ticket_view.html", current_user=current_user,
                           service_technicians=service_technicians, tickets=tickets,
                           selected_ticket_id=selected_ticket_id, all_users=all_users, ticket_comments=ticket_comments,
                           tickets_tasks=tickets_tasks, userProfileForm=edit_form)


@manager_bp.route("/manager_message_board", methods=["GET", "POST"])
@login_required
@roles_required(["manager"])
def manager_message_board():
    create_notice_form = CreateNotice()
    if request.method == "POST":
        if create_notice_form.validate():
            response_object = {
                "status": "success", "message": "Form verification successful"
            }
            return jsonify(response_object), 200
        else:
            return jsonify(create_notice_form.errors), 400
    users = User.query.filter_by(email=current_user.email).first()
    edit_form = EditUser(name=users.name, surname=users.surname, email=users.email, role=users.role[0].name)
    return render_template(
        "manager/manager_message_board.html",
        current_user=current_user,
        userProfileForm=edit_form,
        create_form=create_notice_form
    )

3BIT/ITU/src/smartcity/views/manager_forms.py
"""
File containing the forms for the manager views

@author: Ladislav Vašina
@email: xvasin11@stud.fit.vutbr.cz

@author: Dominik Vágner
@email: xvagne10@stud.fit.vutbr.cz
"""

from wtforms.validators import Email, DataRequired, Length, EqualTo
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, TextAreaField, SelectField

from smartcity.models import User, RolesUsers


class CreateTechnician(FlaskForm):
    name = StringField("Name", [DataRequired(message="Forgot technician name?")])
    surname = StringField("Surname", [DataRequired(message="Forgot technician surname?")])
    email = StringField("Email Address", [Email(), DataRequired(message="Forgot technician email address?")])
    password = PasswordField("Password", [
        DataRequired(message="You must provide a password."),
        Length(min=8, message="Password must be at least 8 characters long."),
        EqualTo("confirm", message="Passwords must match.")
    ])
    confirm = PasswordField("Repeat Password", [EqualTo("password", message="Passwords must match.")])


class CreateServiceTask(FlaskForm):
    name = StringField("Name", [DataRequired(message="Forgot service task name?")])
    description = TextAreaField("Description", [DataRequired(message="Forgot service task description?")])


class CreateNotice(FlaskForm):
    title = StringField("Title", [DataRequired(message="Forgot notice title?")])
    description = TextAreaField(
        "Description",
        [DataRequired(message="Forgot notice description?"),
         Length(min=20, message="Description must be at least 20 characters long.")]
    )
    duration = StringField("Duration", [DataRequired(message="Forgot notice date range?")])

3BIT/ITU/src/smartcity/templates/manager/create_service_task.html
<!--
File containing manager's view for creating service tasks

@author: Ladislav Vašina
@email: xvasin11@stud.fit.vutbr.cz
-->

{% extends "layout.html" %}
{% from "macros/fields.html" import render_text_field, render_boolean_field, render_alert %}

{% block title %} Create service task {% endblock %}

{% block content %}

    <div class="vh-100 d-flex justify-content-center align-items-center">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-12 col-md-10 col-lg-8">
                    <div class="card bg-white shadow-lg" style="border-radius: 0">
                        <div class="card-body p-5">
                            <form id="form" class="mb-3 mt-md-4" method="POST">
                                <i class="las la-city" style="font-size: 36px"></i><b
                                    style="font-size: 32px; margin-left: 10px">SMARTCITY</b>
                                <p class="mt-3 mb-4 mt-1">Create new service task!</p>
                                {# CSRF Token #}
                                {{ form.csrf_token() }}
                                <div id="csrf_token_error" class="text-danger"></div>
                                {# Form fields #}
                                <input hidden type="number" value="{{ current_user.id }}" id="creator_id">
                                <div class="mb-3">
                                    {{ render_text_field(form.name) }}
                                </div>
                                <div class="mb-3">
                                    {{ render_text_field(form.description) }}
                                </div>
                                <button id="recordBtn" name="recordBtn" class="btn btn-search ps-0 pt-0 mb-1"
                                        onclick="record()">
                                    <i class="las la-microphone" id="record"></i> <small class="form-text">
                                    Voice type your description
                                </small>
                                </button>
                                <div class="mb-3">
                                    <label class="form-label" for="technician_select">Assigned technician</label>
                                    <select class="form-select" id="technician_select">
                                        {% for technician in service_technicians %}
                                            <option value="{{ technician.id }}">{{ technician.fullname }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label" for="ticket_select">Assigned ticket</label>
                                    <select class="form-select" id="ticket_select">
                                        {% for ticket in tickets %}
                                            <option value="{{ ticket.id }}">#{{ ticket.id ~', ' ~ticket.name }},
                                                from: {{ ticket.created_at }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="d-grid mt-5">
                                    <button class="btn btn-outline-dark" type="submit">Create service task</button>
                                </div>
                            </form>
                            <div id="alerts" class="mt-3"></div>
                            <div id="success-message" style="display: none;"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $('#recordBtn').on("click", function (e) {
            e.preventDefault();
        });

        function record() {
            let recognition = new webkitSpeechRecognition();
            recognition.lang = "cs-CZE";
            recognition.onresult = function (event) {
                console.log(event);
                document.getElementById('description').value = event.results[0][0].transcript;
            }
            recognition.start();
            recognition.onspeechend = function () {
                recognition.stop();
                console.log('Speech recognition has stopped.');
            }
        }

        // Get form elements by IDs
        const form = document.getElementById("form")
        const successMessage = document.getElementById("success-message");
        const alerts = document.getElementById("alerts");
        const fields = {
            csrf_token: {
                input: document.getElementById('csrf_token'),
                error: document.getElementById('csrf_token-error')
            },
            name: {
                input: document.getElementById('name'),
                error: document.getElementById('name-error')
            },
            description: {
                input: document.getElementById('description'),
                error: document.getElementById('description-error')
            },
            technician_select: {
                input: document.getElementById('technician_select'),
                error: document.getElementById('technician_select-error')
            },
            creator_id: {
                input: document.getElementById('creator_id'),
                error: document.getElementById('creator_id-error')
            },
            parent_ticket: {
                input: document.getElementById('ticket_select'),
                error: document.getElementById('ticket_select-error')
            },
        }

        // React to form submission
        form.addEventListener("submit", async (e) => {
            e.preventDefault();
            // Make JSON out of the form input value
            let data = JSON.stringify({
                csrf_token: fields.csrf_token.input.value,
                name: fields.name.input.value,
                description: fields.description.input.value,
                technician_id: fields.technician_select.input.value,
                creator_id: fields.creator_id.input.value,
                parent_ticket: fields.parent_ticket.input.value
            });

            const response = await fetch("{{ url_for("manager.create_service_task") }}", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: data,
            });
            for (let key in fields) {
                if (fields[key].input.classList.contains("is-invalid")) {
                    fields[key].input.classList.remove("is-invalid");
                    fields[key].error.innerText = "";
                }
            }
            console.log(data)
            if (response.ok) {
                const api_response = await fetch("{{ url_for("api.auth_api.create_service_task") }}", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: data,
                });

                if (api_response.ok) {
                    form.reset()
                    $("#passLength").css('color', '#6c757d');
                    alerts.innerHTML = bootstrap_alert_macro("Service task created", "success")
                    setTimeout(function () {
                        $(".alert").alert('close');
                    }, 3000);
                } else {
                    const message = await api_response.json();
                    alerts.innerHTML = bootstrap_alert_macro(message["message"], "danger")
                }
            } else {
                const errors = await response.json();
                Object.keys(errors).forEach((key) => {
                    fields[key].input.classList.add("is-invalid");
                    fields[key].error.innerText = errors[key][0];
                });
            }
        });

    </script>
{% endblock %}

3BIT/ITU/src/smartcity/templates/manager/create_technician.html
<!--
File containing manager's view for creating new technician

@author: Ladislav Vašina
@email: xvasin11@stud.fit.vutbr.cz
-->

{% extends "layout.html" %}
{% from "macros/fields.html" import render_text_field, render_boolean_field, render_alert %}

{% block title %} Create technician {% endblock %}

{% block content %}
    <br>
    <div class="vh-100 d-flex justify-content-center align-items-center">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-12 col-md-10 col-lg-8">
                    <div class="card bg-white shadow-lg" style="border-radius: 0">
                        <div class="card-body p-5">
                            <form id="form" class="mb-3 mt-md-4" method="POST" novalidate>
                                <i class="las la-city" style="font-size: 36px"></i><b
                                    style="font-size: 32px; margin-left: 10px">SMARTCITY</b>
                                <p class="mt-3 mb-4 mt-1">Create new technician!</p>
                                {# CSRF Token #}
                                {{ form.csrf_token() }}
                                <div id="csrf_token_error" class="text-danger"></div>
                                {# Form fields #}
                                <div class="mb-3 row">
                                    <div class="col">
                                        {{ render_text_field(form.name) }}
                                    </div>
                                    <div class="col">
                                        {{ render_text_field(form.surname) }}
                                    </div>
                                </div>
                                <div class="mb-3">
                                    {{ render_text_field(form.email) }}
                                </div>
                                <div class="mb-3">
                                    {{ render_text_field(form.password) }}
                                </div>
                                <small id="passwordHelpBlock" class="form-text">
                                    <p class="mt-2 mb-0" id="passLength">Minimal password length is 8 characters.</p>
                                </small>
                                <div class="my-3">
                                    {{ render_text_field(form.confirm) }}
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="" id="showPassCheckBox"
                                           onclick="showPassword()">
                                    <label class="form-check-label" for="showPassCheckBox">
                                        Show password
                                    </label>
                                </div>
                                <div class="d-grid mt-5">
                                    <button class="btn btn-outline-dark" type="submit">Create Technician</button>
                                </div>
                            </form>
                            <div id="alerts" class="mt-3"></div>
                            <div id="success-message" style="display: none;"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        // Force email keyboard on mobile devices
        let x = document.getElementById("email");
        x.type = "email";

        function showPassword() {
            let x = document.getElementById("password");
            if (x.type === "password") {
                x.type = "text";
            } else {
                x.type = "password";
            }
            let y = document.getElementById("confirm");
            if (y.type === "password") {
                y.type = "text";
            } else {
                y.type = "password";
            }
        }

        $("#password").keyup(function () {
            let password = $("#password").val();
            let length = /^(?=.*.).{8,}$/
            if (!length.test(password)) {
                $("#passLength").css('color', 'red');
            } else {
                $("#passLength").css('color', 'limegreen');
            }
        });

        // Get form elements by IDs
        const form = document.getElementById("form")
        const successMessage = document.getElementById("success-message");
        const alerts = document.getElementById("alerts");
        const fields = {
            csrf_token: {
                input: document.getElementById('csrf_token'),
                error: document.getElementById('csrf_token-error')
            },
            name: {
                input: document.getElementById('name'),
                error: document.getElementById('name-error')
            },
            surname: {
                input: document.getElementById('surname'),
                error: document.getElementById('surname-error')
            },
            email: {
                input: document.getElementById('email'),
                error: document.getElementById('email-error')
            },
            password: {
                input: document.getElementById('password'),
                error: document.getElementById('password-error')
            },
            confirm: {
                input: document.getElementById('confirm'),
                error: document.getElementById('confirm-error')
            }
        }

        // React to form submission
        form.addEventListener("submit", async (e) => {
            e.preventDefault();
            // Make JSON out of the form input value
            let data = JSON.stringify({
                csrf_token: fields.csrf_token.input.value,
                name: fields.name.input.value,
                surname: fields.surname.input.value,
                email: fields.email.input.value,
                password: fields.password.input.value,
                confirm: fields.confirm.input.value,
                role: 2,
            });

            const response = await fetch("{{ url_for("manager.create_technician") }}", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: data,
            });
            for (let key in fields) {
                if (fields[key].input.classList.contains("is-invalid")) {
                    fields[key].input.classList.remove("is-invalid");
                    fields[key].error.innerText = "";
                }
            }
            if (response.ok) {
                const api_response = await fetch("{{ url_for("api.auth_api.signup") }}", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: data,
                });

                if (api_response.ok) {
                    form.reset()
                    $("#passLength").css('color', '#6c757d');
                    alerts.innerHTML = bootstrap_alert_macro("City manager created", "success")
                    setTimeout(function () {
                        $(".alert").alert('close');
                    }, 3000);
                } else {
                    const message = await api_response.json();
                    alerts.innerHTML = bootstrap_alert_macro(message["message"], "danger")
                }
            } else {
                const errors = await response.json();
                Object.keys(errors).forEach((key) => {
                    fields[key].input.classList.add("is-invalid");
                    fields[key].error.innerText = errors[key][0];
                });
            }
        });

    </script>
{% endblock %}

3BIT/ITU/src/smartcity/templates/manager/manager_dashboard.html
<!--
File containing manager's dashboard view

@author: Ladislav Vašina
@email: xvasin11@stud.fit.vutbr.cz
-->

{% extends "layout.html" %}
{% from "macros/fields.html" import render_text_field, render_boolean_field, render_alert %}

{% block title %} Manager dashboard {% endblock %}

{% block content %}
    <div class="container">
        <br>
        <div class="d-flex justify-content-center align-items-center mt-1">
            <div class="mb-4 col-10">
                <label for="filterStates"><h4>State of tickets you want to be shown</h4></label>
                <select class="form-select mt-2" aria-label="State-filter" id="filterStates">
                    <option value="All states" selected>All states</option>
                    <option value="New">New</option>
                    <option value="Planned">Planned</option>
                    <option value="WorkInProgress">Work in progress</option>
                    <option value="Done">Done</option>
                </select>
            </div>
        </div>
        {% for ticket in tickets %}
            <div class="d-flex justify-content-center align-items-center mt-4 ticketDiv">
                <div class="card col-10 {{ ticket.state.value }}" style="max-width: 1000px;">
                    <div class="row g-0">
                        <div class="col-md-4 d-flex justify-content-center align-items-center">
                            <img
                                    {% if ticket.image_path != None %}
                                        src="{{ ticket.image_path }}"
                                    {% else %}
                                        src="/"
                                    {% endif %}
                                        class="img-fluid rounded-start"
                                        alt="{{ ticket.image_path }}"
                                        style="height: 200px; object-fit: fill;"
                            >
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title"><a
                                        href="{{ url_for("manager.manager_ticket_view") }}?ticketId={{ ticket.id }}"
                                style="text-decoration: none;">{{ ticket.name }}
                                </a>
                                </h5>

                                <p class="card-text">{{ ticket.description[:100] }}</p>
                                <b class="card-text me-5 float-start">Reported
                                    by: {{ all_users[ticket.reporter_id - 1].fullname }}</b>
                                {% if ticket.assignee_id != None %}
                                    <b class="card-text me-5 mb-3 float-start">Assignee: {{ all_users[ticket.assignee_id].fullname }}</b>
                                {% else %}
                                    <p class="card-text me-5 mb-3 float-start">Assignee: Nobody is assigned</p>
                                {% endif %}
                                <button type="button" class="state btn" style="float:right;pointer-events: none;">{{ ticket.state.value }}</button>
                                <p class="col-3">{{ ticket.created_at }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function () {
            $('#filterStates').change(function () {
                if ($('#filterStates').val() == 'All states') {
                    $('.New').show();
                    $('.Progress').show();
                    $('.Planned').show();
                    $('.Done').show();
                } else if ($('#filterStates').val() == 'New') {
                    $('.New').show();
                    $('.Progress').hide();
                    $('.Planned').hide();
                    $('.Done').hide();
                } else if ($('#filterStates').val() == 'Planned') {
                    $('.New').hide();
                    $('.Progress').hide();
                    $('.Planned').show();
                    $('.Done').hide();
                } else if ($('#filterStates').val() == 'WorkInProgress') {
                    $('.New').hide();
                    $('.Progress').show();
                    $('.Planned').hide();
                    $('.Done').hide();
                } else if ($('#filterStates').val() == 'Done') {
                    $('.New').hide();
                    $('.Progress').hide();
                    $('.Planned').hide();
                    $('.Done').show();
                }
            });
        });


        let statesList = document.getElementsByClassName("state");

        for (let i = 0; i < statesList.length; i++) {
            statesList[i].style.fontWeight = "bold";
            if (statesList[i].innerHTML === "New") {
                statesList[i].style.color = "white";
                statesList[i].style.width = "146px";
                statesList[i].classList.add("btn-danger");
            } else if (statesList[i].innerHTML === "Planned") {
                statesList[i].style.color = "black";
                statesList[i].style.width = "146px";
                statesList[i].classList.add("btn-info");
            } else if (statesList[i].innerHTML === "Work In Progress") {
                statesList[i].style.color = "black";
                statesList[i].classList.add("btn-warning");
            } else if (statesList[i].innerHTML === "Done") {
                statesList[i].style.color = "white";
                statesList[i].style.width = "146px";
                statesList[i].classList.add("btn-success");
            }
        }


    </script>
{% endblock %}